### ISSUE TITLE
Vizier API calls

### ISSUE THREAD

**Issue by junhyeokkwak** [kpfromer/jupyter-extensions#2]
## To-do
- [x] Understanding python server folder
- [x] Pull from main repo (transport.ts now in shared utils)
- [x] Set up files & import shared packages
- [x] Create `OptimizerService` class with api call methods
- [x] Create interfaces for study, trial, config

**Comment by junhyeokkwak** [comment]
- [] Understanding python server folder
- [] Handle calls from React frontend
- [] Send API calls to Vizier API
- [] Handle response and send it to React frontend
