### ISSUE TITLE
Create `Dashboard`

### ISSUE THREAD

**Issue by kpfromer** [kpfromer/jupyter-extensions#21]
# Todo

- [x] Show table list of studies
- [x] Create button for studies that launches the `createStudy` view
- [x] Delete buttons for studies (maybe embedded in the table using `material-table`)
- [x] Fetch studies from redux store
