### ISSUE TITLE
Implement API Calls

### ISSUE THREAD

**Issue by kpfromer** [kpfromer/jupyter-extensions#3]
# Todo:

## Generic Slice

This generic slice will abstract the async reducer creation, making it easy to add asynchronous calls to the API.

- [x] Create generic slice

### Studies:

- [x] Fetch studies
- [x] Create Study
- [x] Delete Study

### Trials (all for particular study):

- [x] Fetch trials
- [x] Ask for suggested trials
- [x] Create custom trial
- [x] Add measurement to suggest trials
- [x] Complete trial

### Current View:

- [x] setView
- [x] Dashboard
- [x] Create study
- [x] Particular study
- [x] Trial suggestions page
