### ISSUE TITLE
Create sidebar

### ISSUE THREAD

**Issue by junhyeokkwak** [kpfromer/jupyter-extensions#4]
## To-do
- [x] Understand sidebar component architecture
- [x] Connect sidebar with Redux store
- [x] Generate **Main Dashboard** button
- [x] Add onClick action to **Main Dashboard** button
- [x] Fetch list of studies from store
- [x] Display list of studies
- [x] Attach onClick action to study elements in the list
