### ISSUE TITLE
Create `MainAreaWidget`

### ISSUE THREAD

**Issue by kpfromer** [kpfromer/jupyter-extensions#5]
# Todo:

## View Manager:

- [x] Connect with redux to listen to `view` changes
- [x] Change which child is rendered based on the view (`Dashboard`, `CreateStudy`, `StudyDetails`)
- [ ] Show popup when user is being redirected to new page and has unsaved changes (this will involve changing the structure of the view state in redux)
