### ISSUE TITLE
Suggest Trials Page

### ISSUE THREAD

**Issue by kpfromer** [kpfromer/jupyter-extensions#9]
# Todo:

- [x] Create trials list table component
- [x] Fetch trials from redux (in turn from API) and load them into the list
- [x] Add button to get suggestions from optimizer API
- [x] add button to delete custom inputs
- [x] add inputs for metrics for the user to fill in
- [x] add submit and save to submit metrics and custom trials that users have entered

## User Flow:

User gets suggestions -> user fills in metrics for suggestions -> user submits suggestions
